name: 'Create random file'
description: 'Create file in a random path from base64 encoded string'

inputs:
  base64-file-content: 
    description: 'File content in base64 encoded form'
    required: true
  file-name:
    description: 'Name of the file to write into the path'
    required: false 
    default: "file"

outputs:
  path:
    description: "File path to the file created"
    value: ${{ steps.create-file.outputs.path }}

runs:
  using: "composite"
  steps:
    # Generate path 
    - id: create-file
      run: echo "path=/tmp/$(openssl rand 10 | openssl base64 -A)/${{ inputs.file-name }}" >> $GITHUB_OUTPUT
      shell: bash

    # Create the path and file into the file system 
    - run: mkdir -p ${{ steps.create-file.outputs.path }}
      shell: bash 

    # Create the file from input contents 
    - run: echo ${{ inputs.base64-file-content }} | base64 --decode > ${{ steps.create-file.outputs.path }}
      shell: bash 
      
    - run: echo "File created at path ${{ steps.create-file.outputs.path }}"
      shell: bash 